version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: devsearch/Dockerfile
    container_name: devsearch_app
    restart: always
    env_file:
      - .env.dev
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: devsearch_db
    restart: always
    env_file:
      - .env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
