# Generated by Django 5.1.2 on 2024-11-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_alter_computer_computer_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="computer",
            name="computer_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="printer",
            name="printer_id",
            field=models.IntegerField(null=True),
        ),
    ]
