# Generated by Django 5.1.2 on 2024-11-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_printer_slug_alter_reportlog_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportlog',
            name='file_path',
            field=models.FileField(upload_to='upload'),
        ),
    ]
