# Generated by Django 5.1.2 on 2024-11-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_alter_reportlog_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='slug',
            field=models.SlugField(blank=True, max_length=9, unique=True, verbose_name='URL'),
        ),
    ]
