# Generated by Django 5.1.2 on 2024-11-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_alter_computer_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='slug',
            new_name='computer_slug',
        ),
        migrations.RenameField(
            model_name='printer',
            old_name='slug',
            new_name='printer_slug',
        ),
    ]
