# Generated by Django 5.1.2 on 2024-12-02 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0036_rename_added_by_computer_author_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="computer",
            old_name="author",
            new_name="computer_author",
        ),
        migrations.RenameField(
            model_name="printer",
            old_name="author",
            new_name="computer_author",
        ),
    ]
