# Generated by Django 5.1.2 on 2024-12-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0037_rename_author_computer_computer_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computer",
            name="computer_snumber",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Серийный номер компьютера",
            ),
        ),
        migrations.AlterField(
            model_name="printer",
            name="printer_snumber",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Серийный номер принтера",
            ),
        ),
    ]
