# Generated by Django 5.1.2 on 2024-12-02 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0040_rename_computer_author_computer_author_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="computer",
            old_name="author",
            new_name="computer_author",
        ),
        migrations.RenameField(
            model_name="printer",
            old_name="author",
            new_name="printer_author",
        ),
        migrations.RenameField(
            model_name="printer",
            old_name="printer_id",
            new_name="printers_id",
        ),
    ]
