# Generated by Django 5.1.2 on 2024-12-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_alter_computer_computer_snumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='computer_type',
            field=models.CharField(max_length=150, verbose_name='Тип компьютера'),
        ),
    ]
