# Generated by Django 5.1.2 on 2024-11-15 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Computer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "computer_type",
                    models.CharField(
                        choices=[
                            ("Настольный компьютер", "Настольный компьютер"),
                            ("Моноблок", "Моноблок"),
                            ("Ноутбук", "Ноутбук"),
                        ],
                        max_length=50,
                        verbose_name="Тип компьютера",
                    ),
                ),
                (
                    "computer_inventory",
                    models.CharField(max_length=9, verbose_name="Инвентарный номер"),
                ),
                (
                    "computer_snumber",
                    models.CharField(
                        max_length=50, verbose_name="Серийный номер компьютера"
                    ),
                ),
                (
                    "computer_location",
                    models.CharField(
                        max_length=50, verbose_name="Расположение компьютера"
                    ),
                ),
                ("computer_date", models.DateField(default=datetime.date.today)),
            ],
            options={
                "verbose_name": "Компьютер",
                "verbose_name_plural": "Компьютеры",
            },
        ),
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "printer_type",
                    models.CharField(
                        choices=[
                            (
                                "МФУ HP LaserJet Pro M1536dnf",
                                "МФУ HP LaserJet Pro M1536dnf",
                            ),
                            (
                                "МФУ HP LaserJet Pro M225dn",
                                "МФУ HP LaserJet Pro M225dn",
                            ),
                        ],
                        max_length=50,
                        verbose_name="Тип принтера",
                    ),
                ),
                (
                    "printer_inventory",
                    models.CharField(max_length=9, verbose_name="Инвентарный номер"),
                ),
                (
                    "printer_snumber",
                    models.CharField(
                        max_length=50, verbose_name="Серийный номер принтера"
                    ),
                ),
                (
                    "printer_location",
                    models.CharField(
                        max_length=50, verbose_name="Расположение принтера"
                    ),
                ),
                ("printer_date", models.DateField(default=datetime.date.today)),
            ],
            options={
                "verbose_name": "Принтер",
                "verbose_name_plural": "Принтеры",
            },
        ),
    ]
