# Generated by Django 5.1.2 on 2024-11-15 17:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="computer",
            name="computer_location",
        ),
        migrations.RemoveField(
            model_name="printer",
            name="printer_location",
        ),
    ]
