# Generated by Django 5.1.2 on 2024-11-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_remove_computer_computer_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="computer",
            name="computer_location",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Расположение компьютера"
            ),
        ),
        migrations.AddField(
            model_name="printer",
            name="printer_location",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Расположение принтера"
            ),
        ),
    ]
