# Generated by Django 5.1.2 on 2024-11-16 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_computer_computer_location_printer_printer_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printer",
            name="printer_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Дата добавления"
            ),
        ),
    ]
