# Generated by Django 5.1.2 on 2024-11-16 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_alter_printer_printer_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computer",
            name="computer_date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Дата добавления"
            ),
        ),
    ]
