# Generated by Django 5.1.2 on 2024-11-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_reportlog_remove_computer_id_remove_printer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computer",
            name="computer_location",
            field=models.CharField(
                max_length=50, verbose_name="Расположение компьютера"
            ),
        ),
        migrations.AlterField(
            model_name="printer",
            name="printer_location",
            field=models.CharField(max_length=50, verbose_name="Расположение принтера"),
        ),
    ]
