# Generated by Django 5.1.2 on 2024-11-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_alter_computer_computer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printer",
            name="printer_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
