# Generated by Django 5.1.2 on 2024-11-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_alter_printer_printer_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("serial_number", models.CharField(max_length=100)),
                ("purchase_date", models.DateField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
