# Generated by Django 5.1.2 on 2024-11-25 17:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0014_computer_computer_slug_printer_printer_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="printer",
            name="printer_slug",
        ),
    ]
