# Generated by Django 5.1.2 on 2024-11-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_remove_computer_computer_slug_computer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportlog',
            name='file_path',
            field=models.FileField(upload_to='upldfile/'),
        ),
    ]
