# Generated by Django 5.1.2 on 2024-11-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_reportlog_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='slug',
            field=models.SlugField(blank=True, max_length=9, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='reportlog',
            name='file_path',
            field=models.FileField(upload_to='upload/'),
        ),
    ]
