# Generated by Django 5.1.2 on 2024-11-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_alter_reportlog_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportlog',
            name='file_path',
            field=models.FileField(upload_to='upldfile/'),
        ),
    ]
