# Generated by Django 5.1.2 on 2024-11-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_rename_slug_computer_computer_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='computer_slug',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='printer',
            name='printer_slug',
        ),
        migrations.AddField(
            model_name='printer',
            name='slug',
            field=models.SlugField(blank=True, max_length=9, unique=True, verbose_name='URL'),
        ),
    ]
