# Generated by Django 5.1.2 on 2024-12-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
