# Generated by Django 5.1.2 on 2024-12-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0038_alter_computer_computer_snumber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="computer",
            name="computer_snumber",
            field=models.CharField(
                max_length=50, verbose_name="Серийный номер компьютера"
            ),
        ),
        migrations.AlterField(
            model_name="printer",
            name="printer_snumber",
            field=models.CharField(
                max_length=50, verbose_name="Серийный номер принтера"
            ),
        ),
    ]
