# Generated by Django 5.1.2 on 2024-12-02 18:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0039_alter_computer_computer_snumber_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="computer",
            old_name="computer_author",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="printer",
            old_name="computer_author",
            new_name="author",
        ),
    ]
