# Generated by Django 5.1.2 on 2024-12-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_alter_computer_computer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='computer_location',
            field=models.CharField(max_length=50, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='computer_snumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='computer_type',
            field=models.CharField(max_length=150, verbose_name='Наименование устройства'),
        ),
    ]
