# Generated by Django 5.1.2 on 2024-12-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_alter_computer_computer_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computer',
            options={'verbose_name': 'ПК и ноутбук', 'verbose_name_plural': 'ПК и ноутбуки'},
        ),
        migrations.AlterModelOptions(
            name='printer',
            options={'verbose_name': 'Принтер и сканер', 'verbose_name_plural': 'Принтеры и сканеры'},
        ),
        migrations.AlterField(
            model_name='printer',
            name='printer_location',
            field=models.CharField(max_length=50, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='printer_snumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='printer_type',
            field=models.CharField(choices=[('МФУ HP LaserJet 1536dnf MFP', 'МФУ HP LaserJet 1536dnf MFP'), ('МФУ HP laserJet Pro M1536dnf (CE538A) USB', 'МФУ HP laserJet Pro M1536dnf (CE538A) USB'), ('МФУ HP LaserJet Pro M225dn.A4.print1200[1200dpi', 'МФУ HP LaserJet Pro M225dn.A4.print1200[1200dpi'), ('МФУ, лазерное,HP CF484A LaserJet Pro MFP M225dn (А4)', 'МФУ, лазерное,HP CF484A LaserJet Pro MFP M225dn (А4)'), ('МФУ (принтер+ксерокс+сканер) HP LaserJet 1536dnf MFP', 'МФУ (принтер+ксерокс+сканер) HP LaserJet 1536dnf MFP'), ('Принтер HP Color LaserJet CP5225dn (цветной лазерный формат А3)', 'Принтер HP Color LaserJet CP5225dn (цветной лазерный формат А3)'), ('Принтер А3 струйный, цветной,Epson Stylus L1300', 'Принтер А3 струйный, цветной,Epson Stylus L1300'), ('Принтер лазерный формата А-4 HP CE749A LaserJet Pro P1606n (А4)', 'Принтер лазерный формата А-4 HP CE749A LaserJet Pro P1606n (А4)'), ('Принтер этикеток TSP TTP-244CE', 'Принтер этикеток TSP TTP-244CE'), ('Сканер Plustek Smart Office PL 806. A4', 'Сканер Plustek Smart Office PL 806. A4'), ('Терминал сбора данных Opticon OPH-1004 в комплекте с кредлом CRD-1001+БП', 'Терминал сбора данных Opticon OPH-1004 в комплекте с кредлом CRD-1001+БП'), ('Устройство многофункциональное HP Laser Jet Pro M426fdn', 'Устройство многофункциональное HP Laser Jet Pro M426fdn'), ('Устройство многофункциональное HP LaserJet M443nda', 'Устройство многофункциональное HP LaserJet M443nda'), ('Устройство многофункциональное, печать лазерная HP LaserJet Pro4103fdn', 'Устройство многофункциональное, печать лазерная HP LaserJet Pro4103fdn')], max_length=150, verbose_name='Наименование устройства'),
        ),
    ]
