# Generated by Django 5.1.2 on 2024-12-16 15:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_alter_computer_options_alter_printer_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='computer_type',
            field=models.CharField(choices=[('Компьютер настольный', 'Компьютер настольный'), ('Компьютер HP P3500MT', 'Компьютер HP P3500MT'), ('Компьютер HP Pro 3500MT QB294EA с монитором', 'Компьютер HP Pro 3500MT QB294EA с монитором'), ('Моноблок HP P3520', 'Моноблок HP P3520'), ('Нетбук Prestigio MultiPad Wize 3341 3G', 'Нетбук Prestigio MultiPad Wize 3341 3G'), ('Ноутбук B6M12EA HP Probook 4540s', 'Ноутбук B6M12EA HP Probook 4540s'), ('Ноутбук LENOVO G500', 'Ноутбук LENOVO G500'), ('Ноутбук LENOVO', 'Ноутбук LENOVO'), ('Ноутбук для XDCAM Камкордеров', 'Ноутбук для XDCAM Камкордеров'), ('Рабочая станция HP ProDesk 400 с монитором HP Pro', 'Рабочая станция HP ProDesk 400 с монитором HP Pro'), ('Системный блок HP Pavilion 500-129er', 'Системный блок HP Pavilion 500-129er'), ('Системный блок Apple', 'Системный блок Apple'), ('Монитор Аpple', 'Монитор Аpple'), ('19-дюймовый монитор ПК', '19-дюймовый монитор ПК'), ('Монитор Acer/G236HLBbd/23', 'Монитор Acer/G236HLBbd/23'), ('Монитор HP Z23i23-Inch IPS Monitor D7Q13A4', 'Монитор HP Z23i23-Inch IPS Monitor D7Q13A4')], max_length=100, verbose_name='Тип компьютера'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='printer_type',
            field=models.CharField(choices=[('МФУ HP LaserJet 1536dnf', 'МФУ HP LaserJet 1536dnf'), ('МФУ HP LaserJet Pro M225dn', 'МФУ HP LaserJet Pro M225dn'), ('Принтер HP LaserJet Pro P1606n', 'Принтер HP LaserJet Pro P1606n'), ('МФУ HP Laser Jet Pro M426fdn', 'МФУ HP Laser Jet Pro M426fdn'), ('Принтер HP Color LaserJet CP5225dn', 'Принтер HP Color LaserJet CP5225dn'), ('МФУ HP LaserJet Pro4103fdn', 'МФУ HP LaserJet Pro4103fdn'), ('МФУ HP LaserJet M443nda', 'МФУ HP LaserJet M443nda'), ('Canon МФУ IR2520, 3796B003AC', 'Canon МФУ IR2520, 3796B003AC'), ('Принтер Epson Stylus L1300 Color', 'Принтер Epson Stylus L1300 Color'), ('Принтер этикеток TSP TTP-244CE', 'Принтер этикеток TSP TTP-244CE'), ('МФУ Canon IR2530i', 'МФУ Canon IR2530i'), ('Лазерный факс Panasonic KX-FL423RU-B', 'Лазерный факс Panasonic KX-FL423RU-B'), ('Сканер Plustek Smart Office PL 806. A4', 'Сканер Plustek Smart Office PL 806. A4'), ('Canon МФУ IR2520', 'Canon МФУ IR2520')], max_length=150, verbose_name='Наименование устройства'),
        ),
        migrations.CreateModel(
            name='OtherDevice',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_type', models.CharField(max_length=100, verbose_name='Наименование устройства')),
                ('device_inventory', models.CharField(max_length=9, verbose_name='Инвентарный номер')),
                ('device_snumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='Серийный номер')),
                ('device_location', models.CharField(max_length=50, verbose_name='Расположение')),
                ('device_date', models.DateField(default=datetime.date.today, verbose_name='Дата добавления')),
                ('slug', models.SlugField(blank=True, max_length=9, unique=True, verbose_name='URL')),
                ('device_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Периферия',
                'verbose_name_plural': 'Периферия',
            },
        ),
    ]
